import { ArrowRight, MapPin, Sparkles, ShieldCheck } from 'lucide-react';

const booking='https://bareskinstudioict.glossgenius.com/';

const services=[
  {name:'Brazilian Wax',desc:'A smooth, confidence-first service with results that last longer than shaving.',price:'Book online',note:'Recommended maintenance every 4–6 weeks.'},
  {name:'Bikini Line',desc:'A clean-up around the swimsuit line—great for first-time wax clients.',price:'$50',note:'Approx. 15 minutes.'},
  {name:'Full Legs',desc:'Smooth from top to bottom with professional full-leg waxing.',price:'$89',note:'Approx. 30 minutes.'},
  {name:'Brows',desc:'Clean, polished shaping that complements your natural brow.',price:'$28',note:'Approx. 15 minutes.'},
  {name:'Full Face',desc:'Professional facial waxing for a fresh, smooth finish.',price:'$62',note:'Approx. 30 minutes.'},
  {name:'Dermaplane',desc:'Surface exfoliation that removes dead skin buildup and peach fuzz.',price:'$65',note:'Approx. 30 minutes.'}
];

export default function Home(){return <>
  <header className="nav"><div className="wrap navin"><div className="brand">Bare Skin Studio</div><nav className="links"><a href="#services">Services</a><a href="#about">About</a><a href="#membership">Membership</a><a href="#faq">FAQ</a><a className="btn" href={booking}>Book Now</a></nav></div></header>
  <main>
    <section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">Wichita, Kansas • Full-body waxing</div><h1>Smooth skin.<br/>Zero awkwardness.</h1><p>Bare Skin Studio is a private Wichita waxing studio built around one thing: helping you feel comfortable, cared for, and confident in your skin.</p><div className="actions"><a className="btn" href={booking}>Book your wax <ArrowRight size={17} style={{verticalAlign:'middle'}}/></a><a className="btn alt" href="#services">Explore services</a></div></div><div className="visual"><div className="badge"><strong>Comfort comes first.</strong><br/><span className="small">Private appointments, straightforward service, and professional full-body hair removal.</span></div></div></div></section>
    <section className="trust"><div className="wrap trustrow"><span><MapPin size={17}/> Wichita, KS</span><span><Sparkles size={17}/> Waxing specialist</span><span><ShieldCheck size={17}/> Appointment-based studio</span><span>Easy online booking</span></div></section>
    <section className="section" id="services"><div className="wrap"><div className="eyebrow">Popular services</div><h2>Your routine, made smoother.</h2><p className="sectionIntro">Professional waxing without the intimidating spa experience. Start with one of Bare Skin Studio’s most-booked services, or view the complete menu through online booking.</p><div className="cards">{services.map(s=><article className="card" key={s.name}><h3>{s.name}</h3><p>{s.desc}</p><div className="price">{s.price}</div><div className="small">{s.note}</div></article>)}</div><div className="actions"><a className="btn" href={`${booking}services`}>See all services</a></div></div></section>
    <section className="section proof" id="about"><div className="wrap split"><div><div className="eyebrow">The Bare Skin experience</div><h2>Professional waxing should still feel personal.</h2></div><div><p className="quote">“I absolutely loved my experience with Kristen!”</p><p>Clients consistently highlight comfort, communication, and a welcoming experience. Bare Skin Studio specializes in full-body hair removal in a private Wichita studio.</p><p className="small">Google business profile currently shows a 5.0 rating from 31 reviews. Review count may change.</p></div></div></section>
    <section className="section"><div className="wrap split"><div><div className="eyebrow">First time?</div><h2>Here’s how easy it is.</h2><p className="sectionIntro">The website removes friction and sends every ready-to-book visitor directly into the existing GlossGenius scheduling flow.</p></div><div className="steps"><div className="step"><strong>Choose your service.</strong> Browse by area and find the right appointment.</div><div className="step"><strong>Book online.</strong> Pick an available time through GlossGenius.</div><div className="step"><strong>Show up comfortable.</strong> Your appointment is private, straightforward, and judgment-free.</div><div className="step"><strong>Stay consistent.</strong> Rebook on the recommended schedule for the best waxing routine.</div></div></div></section>
    <section className="section" id="membership"><div className="wrap"><div className="membership"><div className="eyebrow">Coming next • Bare Club</div><h2>A better way to stay smooth.</h2><p className="sectionIntro">We’re designing a recurring membership around maintenance, member perks, priority access and better value for loyal clients—without turning the brand into a discount shop.</p><div className="actions"><a className="btn" style={{background:'#fff',color:'#4b4037',borderColor:'#fff'}} href={booking}>Book now</a></div></div></div></section>
    <section className="section faq" id="faq"><div className="wrap"><div className="eyebrow">Waxing FAQ</div><h2>Know before you go.</h2><details><summary>How often should I get a Brazilian wax?</summary><p>Bare Skin Studio recommends roughly every 4–6 weeks for the best maintenance results.</p></details><details><summary>Where is Bare Skin Studio located?</summary><p>11124 E 28th St N, Wichita, KS 67226, inside Utopia N. Greenwich, Suite 109.</p></details><details><summary>What is the cancellation policy?</summary><p>At least 12 hours’ notice is required for changes. The current posted policy lists a 75% charge for cancellations within 12 hours and a 100% charge for no-shows. Confirm the current policy when booking.</p></details><details><summary>Can I book online?</summary><p>Yes. Appointments are booked through Bare Skin Studio’s GlossGenius booking page.</p></details></div></section>
    <section className="cta"><div className="wrap"><div className="eyebrow">Ready when you are</div><h2>Your next smooth-skin day starts here.</h2><div className="actions" style={{justifyContent:'center'}}><a className="btn" href={booking}>Book Bare Skin Studio</a></div></div></section>
  </main>
  <footer className="footer"><div className="wrap">Bare Skin Studio • Wichita, Kansas • <a href={booking}>Book online</a></div></footer>
</>}
