import { ArrowRight, MapPin, Sparkles, ShieldCheck } from 'lucide-react';
import { bookingUrl, memberships, signaturePricing } from '../lib/pricing';

export default function Home(){return <>
  <header className="nav"><div className="wrap navin"><div className="brand">Bare Skin Studio</div><nav className="links"><a href="#services">Pricing</a><a href="#about">About</a><a href="#membership">Membership</a><a href="#faq">FAQ</a><a className="btn" href={bookingUrl}>Book Now</a></nav></div></header>
  <main>
    <section className="hero"><div className="wrap heroGrid"><div><div className="eyebrow">Wichita, Kansas • Full-body waxing</div><h1>Smooth skin.<br/>Zero awkwardness.</h1><p>Bare Skin Studio is a private Wichita waxing studio built around one thing: helping you feel comfortable, cared for, and confident in your skin.</p><div className="actions"><a className="btn" href={bookingUrl}>Book your wax <ArrowRight size={17} style={{verticalAlign:'middle'}}/></a><a className="btn alt" href="#services">View pricing</a></div></div><div className="visual"><div className="badge"><strong>Comfort comes first.</strong><br/><span className="small">Private appointments, straightforward service, and professional full-body hair removal.</span></div></div></div></section>
    <section className="trust"><div className="wrap trustrow"><span><MapPin size={17}/> Wichita, KS</span><span><Sparkles size={17}/> Waxing specialist</span><span><ShieldCheck size={17}/> Appointment-based studio</span><span>Easy online booking</span></div></section>
    <section className="section" id="services"><div className="wrap"><div className="eyebrow">Signature pricing</div><h2>Your routine, made smoother.</h2><p className="sectionIntro">Straightforward pricing for Bare Skin Studio’s most-requested services and combinations. Visit online booking for the complete service menu.</p><div className="cards">{signaturePricing.map(service=><article className="card" key={service.name}>{service.badge&&<div className="offerBadge">{service.badge}</div>}<h3>{service.name}</h3><p>{service.description}</p><div className="price">{service.price}</div>{service.duration&&<div className="small">Approx. {service.duration}</div>}<a className="textLink" href={bookingUrl}>Book this service <ArrowRight size={15}/></a></article>)}</div><div className="actions"><a className="btn" href={bookingUrl}>See all services</a></div></div></section>
    <section className="section proof" id="about"><div className="wrap split"><div><div className="eyebrow">The Bare Skin experience</div><h2>Professional waxing should still feel personal.</h2></div><div><p className="quote">“I absolutely loved my experience with Kristen!”</p><p>Clients consistently highlight comfort, communication, and a welcoming experience. Bare Skin Studio specializes in full-body hair removal in a private Wichita studio.</p><p className="small">Google business profile currently shows a 5.0 rating from 31 reviews. Review count may change.</p></div></div></section>
    <section className="section"><div className="wrap split"><div><div className="eyebrow">First time?</div><h2>Here’s how easy it is.</h2><p className="sectionIntro">The website removes friction and sends every ready-to-book visitor directly into the existing GlossGenius scheduling flow.</p></div><div className="steps"><div className="step"><strong>Choose your service.</strong> Browse by area and find the right appointment.</div><div className="step"><strong>Book online.</strong> Pick an available time through GlossGenius.</div><div className="step"><strong>Show up comfortable.</strong> Your appointment is private, straightforward, and judgment-free.</div><div className="step"><strong>Stay consistent.</strong> Rebook on the recommended schedule for the best waxing routine.</div></div></div></section>
    <section className="section" id="membership"><div className="wrap"><div className="eyebrow">Maintenance plans</div><h2>Consistency, with built-in value.</h2><p className="sectionIntro">Choose a monthly routine or prepay three visits. Membership enrollment and pack redemption are handled directly through Bare Skin Studio.</p><div className="membershipGrid">{memberships.map(plan=><article className="membershipCard" key={plan.name}><div className="offerBadge light">{plan.badge}</div><h3>{plan.name}</h3><div className="price">{plan.price}</div><p>{plan.description}</p><a className="btn lightButton" href={bookingUrl}>Choose {plan.name}</a></article>)}</div><p className="terms">Memberships renew monthly until canceled. One included service may be redeemed per billing cycle and does not roll over. Prepaid packs are non-transferable. Contact Bare Skin Studio before purchase if you have questions about eligibility or redemption.</p></div></section>
    <section className="section faq" id="faq"><div className="wrap"><div className="eyebrow">Waxing FAQ</div><h2>Know before you go.</h2><details><summary>How often should I get a Brazilian wax?</summary><p>Bare Skin Studio recommends roughly every 4–6 weeks for the best maintenance results.</p></details><details><summary>Where is Bare Skin Studio located?</summary><p>11124 E 28th St N, Wichita, KS 67226, inside Utopia N. Greenwich, Suite 109.</p></details><details><summary>What is the cancellation policy?</summary><p>At least 12 hours’ notice is required for changes. The current posted policy lists a 75% charge for cancellations within 12 hours and a 100% charge for no-shows. Confirm the current policy when booking.</p></details><details><summary>Can I book online?</summary><p>Yes. Appointments are booked through Bare Skin Studio’s GlossGenius booking page.</p></details></div></section>
    <section className="cta"><div className="wrap"><div className="eyebrow">Ready when you are</div><h2>Your next smooth-skin day starts here.</h2><div className="actions" style={{justifyContent:'center'}}><a className="btn" href={bookingUrl}>Book Bare Skin Studio</a></div></div></section>
  </main>
  <footer className="footer"><div className="wrap">Bare Skin Studio • Wichita, Kansas • <a href={bookingUrl}>Book online</a></div></footer>
</>}
